[package]
name = "wd-tagger-rs"
version = "0.1.0"
edition = "2021"

[features]
default = []
cuda = ["ort/cuda"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
indicatif = { version = "0.17", features = ["rayon"] }
ndarray = "0.15"
num-traits = "0.2"
ort = { version = "2.0.0-rc.2" }
rayon = "1.10"
serde = { version = "1.0", features = ["derive"] }
walkdir = "2.5"
