[package]
name = "wd-tagger-rs"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = []
cuda = ["ort/cuda"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossbeam-channel = "0.5"
csv = "1.3"
hf-hub = "0.3"
image = { version = "0.25" }
indicatif = { version = "0.17", features = ["rayon"] }
ndarray = "0.15"
ort = { version = "2.0.0-rc.4" }
rayon = "1.10"
serde = { version = "1.0", features = ["derive"] }
walkdir = "2.5"
