name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Release
        run: cargo build --release --verbose

      - name: Packaging
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          mkdir package
          cp target/release/wd-tagger-rs package/wd-tagger-rs

      - name: Packaging
        if: runner.os == 'Windows'
        run: |
          mkdir package
          copy target\release\wd-tagger-rs.exe package\wd-tagger-rs.exe

      - uses: actions/upload-artifact@v4
        with:
          name: wd-tagger-rs_${{ runner.os }}
          path: package
